### ISSUE TITLE
Two typos in README.md

### ISSUE THREAD

**Issue by Kargoneth** [parleer/semver-bash#2]
There are typos in README.md.

Line 3:
Bash-only implementation of [Semantic Versioning 2.0.0](https://semver.org/spec/v2.0.0.html). Correctly parses and compares complex version strings, but with a convenint loose-parsing algorithm that includes support for:
Should be:
Bash-only implementation of [Semantic Versioning 2.0.0](https://semver.org/spec/v2.0.0.html). Correctly parses and compares complex version strings, but with a convenient loose-parsing algorithm that includes support for:

Line 68:
  Validate a verison string as a semantic version
Should be:
  Validate a version string as a semantic version

Line 185:
  Retursn 0 if versionA < versionB
Should be:
  Returns 0 if versionA < versionB

**Comment by parleer** [comment]
Implemented. Thank you.
